### ISSUE TITLE
update_promises test fails sometimes

### ISSUE THREAD

**Issue by sapir** [David-OConnor/seed#81]
It seems to happen when another test panics. I added a panic to one of my tests in the `merge-attrs` 
branch, and got the following:
```
  ---- seed::dom_types::tests::merge_different_attrs output ----
      error output:
          panicked at 'oops', src/dom_types.rs:1431:9
...

  ---- seed::vdom::tests::update_promises output ----
      error output:
          panicked at 'cannot modify the panic hook from a panicking thread', src/libstd/panicking.rs:99:9
  
      JS exception that was thrown:
          RuntimeError: unreachable executed
          std::panicking::rust_panic_with_hook::hfee0088857287f5e@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1392]:0x11d303
          std::panicking::begin_panic::hbb52db289a771dc8@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[6266]:0x1a4d04
          std::panicking::set_hook::hb4aa901e5df5948e@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[2968]:0x163abe
          <seed::vdom::App<Ms, Mdl>>::run::h6974a0b857137a67@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[224]:0x77b1a
          seed::vdom::tests::update_promises::hf39e5b7d86fcc21d@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[667]:0xd8458
          core::ops::function::FnOnce::call_once::h138edd608e53fa1e@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[6103]:0x1a306
          <futures::future::lazy::Lazy<F, R>>::get::hbdd74f92fdede09a@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[368]:0xa55f
          <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h679e659dd2c16847@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantia
          <wasm_bindgen_test::__rt::TestFuture<F> as futures::future::Future>::poll::{{closure}}::{{closure}}::hf6964e778384fd02@http://127.0.0.1:35831/wasm-bindgen-test_bg
          wasm_bindgen::convert::closures::invoke0_mut::hb742e1fd7f1ed33a@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1741]:0
          cbarg0@http://127.0.0.1:35831/wasm-bindgen-test:248:20
          window.__wbg_test_invoke@http://127.0.0.1:35831/:37:38
          __wbg_wbgtestinvoke_7cb78623c45caf3c@http://127.0.0.1:35831/wasm-bindgen-test:261:13
          wasm_bindgen_test::__rt::__wbg_test_invoke::hc29c5496854d23d3@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1030]:0x1
          <wasm_bindgen_test::__rt::TestFuture<F> as futures::future::Future>::poll::{{closure}}::hba1e17724b720a6e@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > Web
          <scoped_tls::ScopedKey<T>>::set::h2c0631d12c00fdc5@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1682]:0x12ecf6
          <wasm_bindgen_test::__rt::TestFuture<F> as futures::future::Future>::poll::h027bed2b453d6636@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.inst
          <alloc::boxed::Box<F> as futures::future::Future>::poll::h5cc15dea138dc8c3@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-funct
          <wasm_bindgen_test::__rt::ExecuteTests as futures::future::Future>::poll::hdca1c41a428258b9@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.insta
          <futures::future::map::Map<A, F> as futures::future::Future>::poll::hd38ea1b75a6600da@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate
          <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h9156cda28ef36195@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.inst
          <alloc::boxed::Box<F> as futures::future::Future>::poll::he7d6878934154090@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-funct
          <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::hfb739fefd52fbee2@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wa
          <futures::task_impl::Spawn<T>>::enter::{{closure}}::h101e3f9bd12f17cd@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[4
          futures::task_impl::std::set::hf47c0b1e18fe8ee8@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1701]:0x12fe5d
          <futures::task_impl::Spawn<T>>::enter::h851ac3033f34fc28@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1141]:0x10a1de
          <futures::task_impl::Spawn<T>>::poll_fn_notify::hae4a04219bf076cf@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[2198]
          <futures::task_impl::Spawn<T>>::poll_future_notify::h33e4757647d66c71@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[4
          wasm_bindgen_futures::_future_to_promise::Package::poll::h67e6d3dfb2d4e5ea@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-funct
          wasm_bindgen_futures::_future_to_promise::{{closure}}::h4171d10b7b9053ca@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-functio
          wasm_bindgen::convert::closures::invoke2_mut::h87ce774e1313d19e@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1052]:0
          cbarg0@http://127.0.0.1:35831/wasm-bindgen-test:1097:20
          __wbg_new_73c7b9beced23b50@http://127.0.0.1:35831/wasm-bindgen-test:1110:34
          js_sys::Promise::new::h5ba4d9a47d564f1d@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1666]:0x12de9b
          wasm_bindgen_futures::_future_to_promise::h8220e7422916ffdc@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[1278]:0x115
          wasm_bindgen_futures::future_to_promise::hb18f1446cf2ecb50@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[2196]:0x1483
          wasm_bindgen_test::__rt::Context::run::h1de5750c65d2f37d@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[215]:0x72f53
          wasmbindgentestcontext_run@http://127.0.0.1:35831/wasm-bindgen-test_bg line 8 > WebAssembly.instantiate:wasm-function[910]:0xf4567
          run@http://127.0.0.1:35831/wasm-bindgen-test:1355:27
          main@http://127.0.0.1:35831/run.js:35:19
  
  failures:
  
      seed::dom_types::tests::merge_different_attrs
      seed::vdom::tests::update_promises
  
  test result: FAILED. 15 passed; 2 failed; 0 ignored
  console.log div contained:
      panicked at 'oops', src/dom_types.rs:1431:9
      panicked at 'cannot modify the panic hook from a panicking thread', src/libstd/panicking.rs:99:9
  
  error: some tests failed
  error: test failed, to rerun pass '--lib'
```

**Comment by MartinKavik** [comment]
I can't reproduce it.

My steps:
Add `panic!` into the test:
```rust
#[wasm_bindgen_test]
    pub fn merge_different_attrs() {
        panic!("ooops");
        let node = el_to_websys(a![
```
And then I tried:
```
cargo make test_h firefox
cargo make test firefox
cargo make test_h chrome
cargo make test chrome
```
Only `merge_different_attrs` failed in each testing.

---

Tested on current `master` branch on Windows 10.

---

@sapir Could you provide more info? OS; how do you run tests; etc?

**Comment by sapir** [comment]
I got this to happen now in the (old) merge-attrs branch, commit 4cd2b939d233d , by adding the panic in the app_builds test. app_builds comes before update_promises in the test output, so I think maybe it's run before update_promises, and maybe this failure only happens if there's a panic in a test that comes before update_promises. It didn't happen when I added the panic in merge_different_attrs, which shows up later in the test output.

With current master (14104e0), update_promises is first in my test output. I successfully reproduced the bug, by adding another test at the very end of vdom.rs, after update_promises:
```rust
    #[wasm_bindgen_test]
    fn fake_test() {
        panic!("oops");
    }
```

It seems to be executed before update_promises. Anyway, update_promises failed.

If it depends on the test order, then that could explain why I wasn't originally getting consistent failures. Also, it may depend on the exact version of the compiler or browser binary.

I'm running Ubuntu 18.10, and I'm running the tests with `wasm-pack test --firefox --headless`.

**Comment by MartinKavik** [comment]
I can reproduce it everywhere with @sapir's instructions.

Fix / workaround:
`src/vdom.rs -> run()`:
```rust
if !std::thread::panicking() {
    panic::set_hook(Box::new(console_error_panic_hook::hook));
}
```

- Does it fail because tests are running in one thread because of wasm/js engine? => Are tests badly isolated?
- Does wasm-pack inject own panic hook, so Seed's one is redundant?

I'll try to investigate it more in the future. Do you have some ideas?

**Comment by MartinKavik** [comment]
@sapir  Could you confirm that referenced merged PR resolves it even for linux and close this issue?

**Comment by sapir** [comment]
Yes, I think it's not happening now
